[document]
author = "Kai Sassnowski – kai-sassnowski.com – @warsh33p"
company-name = ""
slide-size = "16:9"
theme = "krakow"
brand-logo-scale = "100"
disable-smart-templates = "false"
slide-number = "Laravel Worldwide Meetup"

[settings]
drawerPosition = 0.6498881431767338
textViewCursorLength = 0
textViewCursorLocation = 2956
textViewScrollPosition = 4103


[overrides]
hide-bottom-bar = false