[document]
author = "Kai Sassnowski – kai-sassnowski.com – @warsh33p"
company-name = ""
slide-size = "16:9"
theme = "krakow"
brand-logo-scale = "100"
disable-smart-templates = "false"
slide-number = "Laravel Worldwide Meetup"

[settings]
drawerPosition = 0.6999398677089597
textViewCursorLength = 5
textViewCursorLocation = 5872
textViewScrollPosition = 8025


[overrides]
hide-bottom-bar = false